#!/bin/bash -e

cmake -B build \
	-DENABLE_LTO=FALSE \
	-DRUN_IN_PLACE=TRUE \
	-DBUILD_CLIENT=TRUE \
	-DBUILD_UNITTESTS=FALSE \
	-DCMAKE_BUILD_TYPE=Release \
	-DENABLE_GETTEXT=${CMAKE_ENABLE_GETTEXT:-TRUE} \
	-DBUILD_SERVER=FALSE \
	-DENABLE_LUAJIT=TRUE \
	${CMAKE_FLAGS}

cmake --build build --parallel $(($(nproc) + 1))
